### ISSUE TITLE
Connection close by broker, nil username and client id 

### ISSUE THREAD

**Issue by shokaveli** [ckrey/MQTT-Client-Framework#129]
Hi,

So I am setting these fields in the following method :  

`[_sessionManger connectTo:_serverHost port:_serverPort.integerValue tls:NO keepalive:WWMQCLIENT_DEFAULT_KEEPALIVE clean:WWMQCLIENT_DEFAULT_CLEANSESSION auth:YES user:_serverUsername pass:_serverPassword willTopic:nil will:nil willQos:WWMQCLIENT_DEFAULT_QOS willRetainFlag:YES withClientId:clientId];
`

I made sure that the fields are not nil before making this connect call yet I get a connection closed by broker in the logs.  I checked the server logs and I am getting the following reason for disconnect :  

`Closing TCP connection: ConnectionID=46950 MonitorID=46949 ClientID="" Protocol=mqtt-tcp Endpoint="CDT_Events_Sub_EP" UserID="" Uptime=0 RC=105 Clean=0 Reason="The data from the client is not valid" ReadBytes=59 ReadMsg=0 WriteBytes=0 WriteMsg=0 LostMsg=0 WarnMsg=0.
`

It seems its closing the connection due to nil username and client id which i made sure where in fact not nil before connecting.  Somehow these fields are getting lost somewhere.  Any help would be appreciated! 

Thanks

**Comment by ckrey** [comment]
Which kind of MQTT broker are you using?

It may have restrictions on the length and characters in the clientID. Are you using < 24 characters (digits, letters, -)?

**Comment by shokaveli** [comment]
Not sure broker it is, but I will find out.  My client ID looks like this -> 1461595730-26136

**Comment by shokaveli** [comment]
Which is always less than 24 characters and is generated randomly each connection.

**Comment by shokaveli** [comment]
Maybe i am using the session manage incorrectly.  What is the correct way to init and connect using the manager?

**Comment by shokaveli** [comment]
The broker we are using is "IBM MessageSight"

**Comment by shokaveli** [comment]
Ok so I am finally able to successfully connect but only using the MQTTSession class directly.  The session manger is not working for me with the errors I detailed above...

**Comment by ckrey** [comment]
Hi @shokaveli ,

looking again and again at your original post I found the problem:

You are specifying `willRetainFlag:YES` while setting `will:nil`. This is a protocol violation!
Hence the `Reason="The data from the client is not valid"`

> If the Will Flag is set to 0, then the Will Retain Flag MUST be set to 0 [MQTT-3.1.2-15].
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html

**Comment by Royin** [comment]
Hi  @shokaveli @ckrey  ,

I meet this problem too.
I test and soluted!
just because

[_sessionManger connectTo:_serverHost port:_serverPort.integerValue tls:NO keepalive:WWMQCLIENT_DEFAULT_KEEPALIVE clean:WWMQCLIENT_DEFAULT_CLEANSESSION auth:YES user:_serverUsername pass:_serverPassword willTopic:nil will:nil willQos:WWMQCLIENT_DEFAULT_QOS willRetainFlag:YES withClientId:clientId];

this connect method in MQTTSessionManager.m will call 

[self connectTo:host
               port:port
                tls:tls
          keepalive:keepalive
              clean:clean
               auth:auth
               user:user
               pass:pass
               will:YES
          willTopic:willTopic
            willMsg:will
            willQos:willQos
     willRetainFlag:willRetainFlag
       withClientId:clientId];

The method set will:YES , set willMsg:will 

**when set will:YES, the willTopic  and willMsg can not be nil**

so in

[_sessionManger connectTo:_serverHost port:_serverPort.integerValue tls:NO keepalive:WWMQCLIENT_DEFAULT_KEEPALIVE clean:WWMQCLIENT_DEFAULT_CLEANSESSION auth:YES user:_serverUsername pass:_serverPassword willTopic:nil will:nil willQos:WWMQCLIENT_DEFAULT_QOS willRetainFlag:YES withClientId:clientId];

set willTopic:nil or set will:nil is why the error from!
this metho will is NSData...
