### ISSUE TITLE
"ld: framework not found MQTTClient" when MQTTFramework is included

### ISSUE THREAD

**Issue by pabloa** [ckrey/MQTT-Client-Framework#145]
hello

We are following this instructions from the documentation "Or use the dynamic library created in the MQTTFramework target." 

We included dist/MQTTClient.framework on our Xcode project, but it seems it cannot be linked correctly. We are getting a link error:

`Undefined symbols: "_OBJC_CLASS_$_MQTTSession", referenced by ...`

We did other variation by generating a dynamic library and we get now

`Undefined symbols for architecture x86_64: "_OBJC_CLASS_$_MQTTSession", referenced by ...`
or other architecture.

Could you please provide instructions about how to integrate MQTT Client?
We used to work with version 0.4 with no issues. But we cannot make it work with version 0.7.8 on XCode 7.3.1

Thank you

Pablo

**Comment by ckrey** [comment]
Sorry for the late reply.

To be honest, most of the users of the library use CocoaPods as a package manager for integration of the framework into the project. This works well and because of the large number of users is quite stable and tested.

The Framework deliverable was done in the early days of the project and was quite a hack. I suggest you try to use CocoaPods.
