### ISSUE TITLE
SRWebSocket.h not found

### ISSUE THREAD

**Issue by Abhishek9634** [ckrey/MQTT-Client-Framework#254]
Hi,

There is not <SocketRocket/SRWebSocket.h> file in this project.
Can you tell me from where you are getting this file

**Comment by JerOdd** [comment]
My issue is related to this thread so I am posting it there: 

Apparently MQTTWebsocketTransport.m is not included as a Target Membership of the framework.
Also if it is, <SocketRocket/NSURLRequest+SRWebSocket.h> is needed. 
Otherwise this line:
`urlRequest.SR_SSLPinnedCertificates = self.pinnedCertificates;` 
will prevent the framework to build.

Kind regards.

**Comment by Abhishek9634** [comment]
I have import all files and it is building successfully in my framework project
but when try to create cocopod and run in sample project i m getting same error <SocketRocket/SRWebSocket.h> not found. For work around i have deleted MQTTWebsocketTransport.h amd .m file. :(

**Comment by ckrey** [comment]
There is a dependency to SocketRocket in the CocoaPod.
Websockets are an optional Subspec as documented: https://cocoapods.org/?q=mqttclient

If you manually import the files, you have to take care of the dependencies yourself
