### ISSUE TITLE
MQTTWebSocketTransport.m not in target Membership of the framework

### ISSUE THREAD

**Issue by JerOdd** [ckrey/MQTT-Client-Framework#255]
Hi,

I posted this comment in a comment on another thread but I think this thread is now closed:

Apparently MQTTWebsocketTransport.m is not included as a Target Membership of the framework.
Also if it is, <SocketRocket/NSURLRequest+SRWebSocket.h> is needed.
Otherwise this line:
`urlRequest.SR_SSLPinnedCertificates = self.pinnedCertificates;`
will prevent the framework to build.

Kind regards.

**Comment by ckrey** [comment]
You are correct. The Framework does only include the core components.
One reason for this is to avoid the dependency on an external package.

To be honest, because of such problems I personally only use CocoaPods.
I have no idea how to do it right for every use case and environment with frameworks. But maybe you can help
