### ISSUE TITLE
EXEC_BAD_ACCESS on MQTTDecoder when using invalid credentials

### ISSUE THREAD

**Issue by TiagoVeloso** [ckrey/MQTT-Client-Framework#53]
My broker is emqtt (https://github.com/emqtt/emqttd).

When I am sending invalid credentials to the broker I get the following message, which is OK.

> MQTTSession eventCode: connection refused (1) Error Domain=MQTT Code=4 "MQTT CONNACK: bad user name or password" UserInfo=0x17427f9c0 {NSLocalizedDescription=MQTT CONNACK: bad user name or password}

But I am also getting a EXEC_BAD_ACCESS on line 188 of `MQTTDecode.m`

This was what I got from the debugger:

    _dataBuffer	NSMutableData *	nil	0x0000000000000000
    _delegate	id	0x0	0x0000000000000000

    Printing description of msg:
    <MQTTMessage: 0x17403c000>
    Printing description of msg->_type:
    (UInt8) _type = '\x02'
    Printing description of msg->_data:
    <0004>
    Printing description of msg->_data->_bytes:
    (void *) _bytes = 0x0000000174017d40

**Comment by ckrey** [comment]
Probably you are deallocating your MQTTSession after receiving the `connection refused`

The MQTT protocol continues by shutting down the session and needs the MQTTSession, MQTTDecoder and MQTTEncoder for that.

I suggest you keep the MQTT Session for a while. It is save to deallocate after receiving the MQTTSessionClosed or MQTTSessionClosedByBroker event.

**Comment by ckrey** [comment]
...and for a new start with changed credentials, you don't need to create a new MQTTSession

**Comment by CarlLee** [comment]
@ckrey Will MQTTSession automatically resubscribe to topics if i change credentials?

**Comment by ogres** [comment]
@CarlLee No, MQTTSession will not , you must subscribe yourself , 
but if you are using MQTTSessionManager , this behavior is implemented in it , when it reconnects , it always re-subscribes to the given topics.

**Comment by TiagoVeloso** [comment]
Now that I have some more time. I am using `MQTTSessionManager` object to manage my MQTT connection.

How would I handle changing credentials when receiving a Code 4 error?

I have the following:

	- (void) handleMQTTSessionChanges{
	    switch (self.manager.state) {
	        case MQTTSessionManagerStateStarting:
	            DDLogDebug(@"MQTT session starting");
	            break;
	        case MQTTSessionManagerStateConnecting:
	            DDLogDebug(@"MQTT session connecting");
	            break;
	        case MQTTSessionManagerStateConnected:
	            DDLogDebug(@"MQTT session connected");
	            break;
	        case MQTTSessionManagerStateClosing:
	            DDLogDebug(@"MQTT session closing");
	            break;
	        case MQTTSessionManagerStateClosed:
	            DDLogDebug(@"MQTT session closed");
	            if ([self.manager.lastErrorCode.domain isEqualToString:@"MQTT"] &&
	                self.manager.lastErrorCode.code == 4){
	
	            }
	            break;
	        case MQTTSessionManagerStateError:{
	            DDLogDebug(@"MQTT session error");            
	            break;
	        }
	        default:
	            break;
	    }
	}

Is it enough to call `[MQTTSessionManager connect withHost:WithPort.......]` with new credentials?

**Comment by ckrey** [comment]
Yes, that should do it.

**Comment by crsantos** [comment]
When I have an expired credential this EXEC_BAD_ACCESS issue seems to happen frequently.
From my investigations, this is due to a stream delegate still opened on ```MQTTSession connect:```
Well, if ```connectToHost:port:usingSSL:``` is called again, the encoder and decoder will be replaced by new ones, never cutting the cord with the old delegate, like it's done here:

    self.encoder = [[MQTTEncoder alloc] initWithStream:...
    ...
    self.decoder = [[MQTTDecoder alloc] initWithStream:..

A simple fix is to call ```close``` on both ```decoder``` and ```encoder``` (that will **clear** the old delegate a kill the previous stream) (like this here)[https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClient/MQTTSession.m#L513]:

    if(!connectError){
        [self.encoder close];
        [self.decoder close];
        
        self.encoder = [[MQTTEncoder alloc] initWithStream:...

I can submit a PR if you agree with this solution

**Comment by crsantos** [comment]
Well, I've spotted some other EXC_BAD_ACCESS issues due to trying to mess with reconnect.
MQQTSession delegate is also "alive" when the new session is created.

I was thinking on @TiagoVeloso 's case, maybe instead of trying to "override" session manager's reconnect behaviour, why not allow a "reconfig" of user/pass via delegation before trying the timed reconnect? Like a new delegate method on ```MQTTSessionManagerDelegate```:

    - (NSString *)authenticationPasswordForSessionManager:(MQTTSessionManager *)sessionManager;

What do you guys think? Would that be absurd?

**Comment by ckrey** [comment]
To be honest, I see your problem, but I cannot understand where it comes from.

When MQTTSession encounters a problem or the Connect is rejected by the broker, it calls [self error:...] and closes the streams as well as cuts the delegate connection.

I guess you are trying to do a re-connect in the handleEvent delegate method, which is a bad idea, because the "old" session is still around.

A better way to to it would be e.g. to start a timer and try re-connect after a few seconds or go back to the UI and ask the user to input the correct credentials.

**Comment by ogres** [comment]
When broker closes connection because of credentials and you got Event with not-connected state, you can check if the connection was actually closed via

```
    MQTTSessionStatus status = session.status;
    if(status == MQTTSessionStatusClosed) {
            [self clientDidDisconnect];
    }
```
after it, you can re-connect again, you can also add ~1 seconds delay to make sure its closed and cleared.

**Comment by crsantos** [comment]
I'm not doing a re-connect in the ```handleEvent:```. That is what the ```MQTTSessionManager``` ```self.reconnectTimer```is already doing. I'm not even changing your ```MQTTSessionManager```.

And IMHO, "waiting a few secs" is not a proper way to handle this. Correct session delegates cleanups should be the way

**Comment by crsantos** [comment]
@ogres that behaviour is the one implemented on the existing ```MQTTSessionStatusClosed```, with ```reconnectTimer```. It just doesn't allow credentials to be updated after a ```connect:```
I guess a better way is to implement my own manager that will fit my needs. I was just thinking this could be a useful feature.

**Comment by ckrey** [comment]
Sorry, I didn't mean to offend you.
I am happy to see you using the library differently than I did.
Just go ahead with your proposed changes

**Comment by crsantos** [comment]
Oh, not at all :) I'm sorry if I sounded like that, never meant it!
Always glad to contribute! And thanks for your work on the library!

**Comment by wishsoul** [comment]
I know self is only retain in init, copy several methods，so if I access self in a for but self was released. I will get this crash. How to solve this problem? 
![2015-11-06 11 32 52](https://cloud.githubusercontent.com/assets/6064240/10988766/5552cf84-847a-11e5-976a-b9c232f3edc0.png)

**Comment by ckrey** [comment]
Might be related to #61 if you are using multiple threads sending messages. Please re-test
