### ISSUE TITLE
Can this be made to work over WebSockets?

### ISSUE THREAD

**Issue by ertanden** [ckrey/MQTT-Client-Framework#62]
Hi, I'm currently using this library in an app and thanks for all the hard work.

We were thinking of moving all our backend communication to ports 80/443 (since enterprise environments usually only allow those outgoing ports) but unfortunately this library does not use WebSockets so it doesn't look possible currently.

It would be nice if this client provided MQTT over WebSockets with an option.

**Comment by ckrey** [comment]
@ertanden, if I understand you right you are talking about changing ports.

This is no problem: Just run your broker listening on 80/443 and connect from the client to 80/443.

I know from experience that some enterprises block outgoing ports other than 80/443 and run a proxy to control web traffic, which is IMHO not really helpful with regards to security.

To answer your question, adding WebSockets support is not trivial and not currently planned

**Comment by ckrey** [comment]
... but I would definetly accept contributions to it

**Comment by jpmens** [comment]
@ertanden can you elaborate on *why* Websockets? While I possibly understand you need particular outgoing ports for communicating over corporate infrastructure and that is possible (as @ckrey said), *why* Websockets? What do you think you can achieve by replacing the protocol?

**Comment by ckrey** [comment]
Another request:
Does MQTTClient support mqtt-over-websocket? 

Answer:
No, it doesn't. To be honest, I don't understand the use case for MQTT over Websockets for a non-browser app

**Comment by vineetdgithub** [comment]
I'm new to MQTT, and even I don't quite understand why mqtt-over-websockets was designed.

But I was forced to look into it because of my use case. The  requirement for mqtt-over-websockets originates mainly for designing a gracefully scalable backend architecture. Imagine a server back-end that consists of hundreds of MQTT brokers. Each broker is running independently of the other. There is no replication of messages between brokers. If you need extra capacity to handle load, you add another broker. If a broker goes down, it takes down all channels and TCP connections with it. All brokers are fronted by HAProxy which routes incoming TCP connections to one of the many brokers.

To achieve an architecture like above, one needs to make sure that all clients interested in publishing or subscribing on channel X must be routed to that particular broker that is currently hosting channel X. 

E.g. there are two clients (c1 & c2) are interested in talking over channel X.  Say c2 connects to HAProxy first and HAProxy picks up broker number 5 from a pool of 10 brokers and forwards this connection to broker 5. HAProxy decides this based on one of the load balancing algorithms it supports. When c1 connects to HAproxy with an intention of talking over channel X, then HAProxy must send c1 to broker number 5 where channel X is created by c2 (e.g. by calling subscribe on channel X).

Now in order to achieve this routing, HAProxy needs to monitor MQTT transaction all the way to the point of the first PUBLISH or first SUBSCRIBE message which contains a channel name. Unfortunately CONNECT message doesn't carry channel name.  Since PUBLISH or SUBSCRIBE are a separate message from CONNECT message they can come in a separate TCP segment. I still haven't figured out if HAProxy can be configured to do this complex load balancing.

mqtt-over-websockets solves this problem for me. Because it starts with HTTP request, it is possible to specify a channel name in the URL or request header. HAProxy knows very well how to load balance and stick a connection based on URL or headers. 

This design assumes that either client will not call second PUBLISH or SUBSCRIBE on this session for another channel. After their conversation is over, both clients will immediately unsubscribe from channel X and disconnect connections.

So choices I have to achieve this design without changing broker or the client are as follows

Choice 1
- Use MQTT client (i.e. no web socket)
- Figure out HAProxy's configuration to perform load balancing and sticky rules

Choice 2
- Use MQTT client (i.e. no web socket)
- Use standard TCP load balancing algorithms of HAProxy
- Use clustering and message replication between brokers

Choice 3
- Use mqtt-over-websockets client
- Use HTTP based load balancing and stickiness of HAProxy
- Use any number of brokers in the backend (even mix them together like Mosca, Mosquitto etc)

**Comment by ckrey** [comment]
What I want to suggest to you is to look if you can use the clientID or a part of the clientID to indicate the channel. As it is part of the connect message it can be inzerpreted by the balancer.

**Comment by ckrey** [comment]
Thanks @vineetdgithub for finding hapim/IOS-MQTT-Websocket-Client/tree/master/MQTTClient/MQTTSDK

I wasn't aware of that yet. This fork was done almost a year ago from my repo.
It seems @openmason added websockets using socketrocket. Unfortunately the fork was never
consolidated.

I will take a look.
The @openmason just replaced CFNetwork calls by SocketRocket.

I will try to bring the forks together...

**Comment by ckrey** [comment]
the @openmason fork was forked and extended by @allting

https://github.com/allting/IOS-MQTT-Websocket-Client

**Comment by allting** [comment]
@ckrey 
I'm using it in my project.
It works with SocketRocket 0.4.1
thank you.

**Comment by jpmens** [comment]
Can this cause licensing issues? Particularly in view of the Eclipse idea?

**Comment by ckrey** [comment]
I know the Paho Java client offers Websockets. I will have to check with regards to SocketRocket.

Anyhow I plan to make the transport protocol beneath MQTTClient configurable. We could then include CFNetwork in eclipse, but exclude Websockets or others...

**Comment by ckrey** [comment]
SocketRocket has an Apache2 license, which from my point of view is NOT compatible with EPLv1

**Comment by ertanden** [comment]
@ckrey @jpmens On your question of "why websockets", well because it simplifies things a lot. Let me explain;

We have a deployment where all our services run on a single instance (including Nginx, MQTT Broker and backend applications). For scalability we use a load balancer and multiple identical instances. So it's not possible to run MQTT Broker on ports 80/443 since NGinx is the one using those ports. If WebSockets were available, then we could use Nginx to proxy WebSocket connections to another port. In fact, for our browser clients we use this. But for our IOS clients, we have to open a separate port right now.

WebSockets solve a lot of problems from enterprise point of view. It really becomes a burden to have all enterprises open ports other than 80/443.

**Comment by jpmens** [comment]
IMO that's a bit like asking for SMTP over Websockets ... ;-)

**Comment by ertanden** [comment]
@jpmens apples to oranges. When you deal with customers and IT guys that have no clue about MQTT etc it's not easy to make them open ports. SMTP like HTTP is a pretty old protocol that has been already accepted by many. 

WebSockets (or HTTP) also have the advantage of configuring stickiness. Amazon Load Balancer currently supports stickiness only for HTTP and not for bare TCP connections. So that's another advantage of MQTT over WebSockets.

**Comment by ckrey** [comment]
Done, needs some regression testing though

**Comment by ertanden** [comment]
Fantastic! @ckrey :+1:

**Comment by liltimtim** [comment]
Hello, I'm looking over this thread and I saw ckrey mark this as "done".  What does "done" mean?  Does it mean that this project now supports MQTT over WebSockets or do I need to go to the forked version?

**Comment by ckrey** [comment]
It is done and it is part of the master. The fork is gone

**Comment by liltimtim** [comment]
okay awesome.  I have tried connecting to the example MQTT server at http://test.mosquitto.org/ws.html

I configure everything as if I'm connecting to a native MQTT client (which I can do successfully) however when I try to connect to the web socket test server it fails.  Is there extra configs one must do in order to connect to a web socket using your library? I didn't see anything in the documentation regarding this so I'm unsure what I'm doing incorrectly.

**Comment by jpmens** [comment]
I think the URL you want to connect to is http://test.mosquitto.org:8080/ws

**Comment by ckrey** [comment]
When you want to use websockets, you have to create a Websocket transport and assign it to MQTTSession's transport property, then connect:
```
        MQTTWebsocketTransport *websocketTransport = [[MQTTWebsocketTransport alloc] init];
        websocketTransport.host = parameters[@"host"];
        websocketTransport.port = [parameters[@"port"] intValue];
        websocketTransport.tls = [parameters[@"tls"] boolValue];
        if (parameters[@"path"]) {
            websocketTransport.path = parameters[@"path"];
        }
        websocketTransport.allowUntrustedCertificates = [parameters[@"allowUntrustedCertificates"] boolValue];

        transport = websocketTransport;```

The interface is described in MQTTSession.h / MQTTTransport.h / MQTTWebsocketTransport.h and in MQTTClientTests/MQTTTestHelpers.m

**Comment by liltimtim** [comment]
Hello, I've ran your Pod file install however, it does not install these header files.  
![screen shot 2016-01-20 at 12 39 41 pm](https://cloud.githubusercontent.com/assets/4106065/12457520/e94f74b6-bf72-11e5-8216-4a413763fe30.png)

![screen shot 2016-01-20 at 12 06 59 pm](https://cloud.githubusercontent.com/assets/4106065/12456575/6e1cbf82-bf6e-11e5-9f55-190997d3818c.png)

Attached are images the Core files are installing and I'm using version 0.6.4 however the pod file isn't working? 
![screen shot 2016-01-20 at 12 08 41 pm](https://cloud.githubusercontent.com/assets/4106065/12456757/39ae1ed4-bf6f-11e5-93d6-8d5bb8d493a9.png)
As you can see from my terminal screenshot, it's installing 0.6.4.  So even with this "how to" I am unable to implement this due to the fact some files aren't installing via CocoaPods.  I'm using the MQTTClient pod file as specified here https://cocoapods.org/pods/MQTTClient.

@jpmens on the website I posted it states HOW TO connect to the server and not at that address.  Also, you are using the HTTP protocol not web socket protocol as described here http://test.mosquitto.org/ws.html.  They state in order to connect to the MQTT client you must use the URI ws://test.mosquitto.org/mqtt

**Comment by liltimtim** [comment]
Also, after manually installing your files by downloading the source, I believe your Master Repo has several issues. 

One of which is this file:

//
//  MQTTFramework.h
//  MQTT-Client-Framework
//
//  Created by Terry Latanville on 2015-11-25.
//  Copyright © 2015-2016 Christoph Krey. All rights reserved.
//

#import <UIKit/UIKit.h>

#import "MQTTSSLSecurityPolicy.h"
#import "MQTTDecoder.h"
#import "MQTTEncoder.h"
#import "MQTTMessage.h"
#import "MQTTSession.h"
#import "MQTTPersistence.h"
#import "MQTTSessionManager.h"

//! Project version number for MQTTFramework.
FOUNDATION_EXPORT double MQTTFrameworkVersionNumber;

//! Project version string for MQTTFramework&lt;.
FOUNDATION_EXPORT const unsigned char MQTTFrameworkVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <MQTTFramework/PublicHeader.h>


The biggest issue here is that you try to import "MQTTEncoder.h".  If you search your entire repo, this file doesn't exist attached below is the screenshot showing this

<img width="1049" alt="screen shot 2016-01-20 at 1 32 39 pm" src="https://cloud.githubusercontent.com/assets/4106065/12458969/5713200e-bf7a-11e5-9826-efd41ec76c71.png">

So I'm seriously lost here.  I also tried using your Framework file.  It too has missing dependencies.  Was the merge possibly faulty/incomplete?

**Comment by sudhamoorthi** [comment]
I am using MQTT over websocket but i am not able to receive the message. The newmessage method in MQTTSessionDelegate is used to receive the message. but the message is not arrived here.
